python: can't open file '/tmp/gptme-evals-3n8x8hvv/prime.py': [Errno 2] No such file or directory
