python: can't open file '/tmp/gptme-evals-mee44u5v/prime.py': [Errno 2] No such file or directory
