python: can't open file '/tmp/gptme-evals-ato9ohrf/prime.py': [Errno 2] No such file or directory
