python: can't open file '/tmp/gptme-evals-79q1li4f/prime.py': [Errno 2] No such file or directory
