python: can't open file '/tmp/gptme-evals-_t54kvtk/prime.py': [Errno 2] No such file or directory
