python: can't open file '/tmp/gptme-evals-4_h9dyet/prime.py': [Errno 2] No such file or directory
