python: can't open file '/tmp/gptme-evals-sdqtcy_u/prime.py': [Errno 2] No such file or directory
