python: can't open file '/tmp/gptme-evals-_dtvdj79/prime.py': [Errno 2] No such file or directory
